title: ⏰ HCI Conference Deadlines
description: Countdowns to top HCI conference deadlines
author: Andrea Bianchi

domain: 'hci-deadlines.github.io'
baseurl: ''

twitter_hashtag: hci-deadlines
github_username: hci-deadlines
github_repo_confdatabase: conf-database

markdown: kramdown
ga_id:

include: ['_pages']
exclude: ['CLAUDE.md', 'README.md', 'LICENSE', 'utils', 'bin', 'Gemfile', 'Gemfile.lock', 'vendor']
